from tkinter import *
def Fahrenheit():
   tempvalue=float(fRes.get())
   convert_temp_val=(tempvalue-32)*(5/9)
   cRes.set(convert_temp_val)
def Celsius():
   tempvalue=float(cRes.get())
   convert_temp_val=(tempvalue*9/5) + 32
   fRes.set(convert_temp_val)
windows = Tk()
windows.geometry("250x100")
windows.title("Temp Conv.")
fLabel=Label(windows,text="Fahrenheit")
cLabel=Label(windows,text="Celsius")
fRes=StringVar()
fRes.set("32.0")
cRes=StringVar()
cRes.set("0.0")
fEntry=Entry(windows,textvariable=fRes)
cEntry=Entry(windows,textvariable=cRes)
fButton=Button(windows,text=">>>>",bg="gray",command=Fahrenheit)
cButton=Button(windows,text="<<<<",bg="gray",command=Celsius)
fLabel.grid(row=0,column=0)
cLabel.grid(row=0,column=1)
fEntry.grid(row=1,column=0)
cEntry.grid(row=1,column=1)
fButton.grid(row=2,column=0)
cButton.grid(row=2,column=1)
windows.mainloop()
